language: java
jdk:
- oraclejdk7
- openjdk6
env:
  global:
  - secure: B/EziRXlIeuw0VsY+plwtQoVS/uDT1PQP3hePPkKFC5P1Jt7a3KOmugAYTM/eRtQXkLyPfFhqRzWqzE5MUaTzkty+jbbOIcFa5fa2TPtQCcWEWWmZYOi+CkylDtwiuYELNIaMvxosI+opPnPtEF3t5CDuu4tJ8I6u2p/e77a+iI=
  - secure: LPM+GWoak4FHICRrN1UdRbJu04q2TwNyVPEs3G1VJgrEfKXVv6dquzi7L3vZcE49qFh5WcTT8ypECrIYf10qXqVPdvp++qyGKnF6o9rUahpGWZFsWA9711/x/skMgE2+PmylZWDR+QUX+WqJJcKbdKHRgdAZV9vggZ9eab4XgUA=
addons:
  sauce_connect: true
notifications:
  email:
    recipients:
      - kaj.qvickstrom@gmail.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: change
